workspace:
  base: /go
  path: src/github.com/fnbk/hello

pipeline:
  build:
    image: golang:latest
    commands:
      - go test
      - go build

  docker:
    image: plugins/docker
    repo: hvt1/hello
    debug: true
    secrets: [ docker_username, docker_password ]

