workspace:
  base: /go
  path: src/github.com/fnbk/hello

pipeline:
  build:
    image: golang:latest
    commands:
      - go test
      - go build

  docker:
    image: plugins/docker
    repo: fnbk/hello
    debug: true
    secrets: [ docker_hub_username, docker_hub_password ]
