workspace:
  base: /go
  path: src/github.com/high-value-team/hello

pipeline:
  build:
    image: golang:latest
    commands:
      - go test
      - go build

  docker:
    image: plugins/docker
    repo: hvt1/hello
    debug: true
    secrets: [ docker_username, docker_password ]

  rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: hello/hello
    docker_image: hvt1/hello
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180



